directories:
  output: release
  buildResources: build
appId: com.rohit.billing
productName: Rohit Billing Suite
files:
  - filter:
      - dist/spa/**
      - electron/**
extraMetadata:
  main: electron/main.mjs
win:
  target:
    - target: appx
      arch:
        - x64
appx:
  displayName: Rohit Billing Suite
  identityName: com.rohit.billing
  backgroundColor: '#ffffff'
  publisher: CN=Rohit
electronVersion: 31.7.7
